fix undefined constants.
PrestaShop/php-dev-tools pull request #54
Opened 2021-04-14 20:45 UTC by SebSept

In fact it only hides the errors, but it do the jobs (it seems).

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Avoid undefined constants : makes phpstan tests fail on CI
| Type?             | bug fix 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | #53 
| How to test?      | run the analyse , ?(use php 7.4)
| Possible impacts? |  may hide problems inside Prestashop, but this is not to test Prestashop.

2021-04-16 14:39 UTC, PierreRambaud requested changes
I'm not sure it's the right way to handle it, here, you're not fixing the undefined constant, you just hide them :thinking:

2021-04-16 15:15 UTC, SebSept commented
For sure it's an hard and ugly solution.
defining the missing constants is way better.

But if I test against old version of Prestashop, 1.7.5.2 for example, there is another error running on php8.
```
» _PS_ROOT_DIR_=/home/http/tests/prestashop/PrestaShop-1.7.5.x php80 ./phpstan.phar analyse ./
Note: Using configuration file /home/http/tests/phpstan-prestashop/blockreassurance/phpstan.neon.
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/http/tests/prestashop/PrestaShop-1.7.5.x/vendor/icanboogie/common/lib/helpers.php on line 306
```
This error is not solved by adding constants.

But it's solved with the @ trick ... 

That's not a problem for me, I won't test old versions against php8, So this error may not happen on real use cases.. Not for me at least.

Maybe we can define the constants and forget about the rest ... 🤔

2021-04-16 18:29 UTC, PierreRambaud commented
> For sure it's an hard and ugly solution.
> defining the missing constants is way better.
> 
> But if I test against old version of Prestashop, 1.7.5.2 for example, there is another error running on php8.
> 
> ```
> » _PS_ROOT_DIR_=/home/http/tests/prestashop/PrestaShop-1.7.5.x php80 ./phpstan.phar analyse ./
> Note: Using configuration file /home/http/tests/phpstan-prestashop/blockreassurance/phpstan.neon.
> PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/http/tests/prestashop/PrestaShop-1.7.5.x/vendor/icanboogie/common/lib/helpers.php on line 306
> ```
> 
> This error is not solved by adding constants.
> 
> But it's solved with the @ trick ...
> 
> That's not a problem for me, I won't test old versions against php8, So this error may not happen on real use cases.. Not for me at least.
> 
> Maybe we can define the constants and forget about the rest ...

You are using php8, PrestaShop is not compatible with it yet :)

2021-04-16 20:59 UTC, SebSept commented
Sure and I did not even start to test my modules with php8.
I just saw this error on a github action.

2021-04-20 20:53 UTC, SebSept reviewed
that's fixed

2021-04-21 07:43 UTC, PierreRambaud commented on phpstan/bootstrap.php
> +define('_THEME_NAME_', 'default-bootstrap');
If you do it, you can remove the line 122

2021-04-21 19:31 UTC, SebSept commented
replaced by #59

2021-04-21 19:31 UTC, closed without merging