Add autoindex lib to php-dev-tools
PrestaShop/php-dev-tools pull request #63
Opened 2021-06-09 15:44 UTC by Quetzacoalt91

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add autoindex v2 to php-dev-tools libraries
| Type?             | new feature
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | /
| How to test?      | /
| Possible impacts? | /

2021-06-10 09:51 UTC, atomiix approved these changes

2021-06-14 08:42 UTC, matthieu-rolland approved these changes

2021-06-14 08:58 UTC, PierreRambaud requested changes
I don't know if we can add it into this repository.
The original work has been released under the MIT license, and it's a fork :thinking: 
ping @eternoendless @ttoine

2021-06-17 14:16 UTC, eternoendless commented
I don't think it's a license conflict if we don't package and distribute the dependencies ourselves.

2021-06-17 14:24 UTC, PierreRambaud approved these changes

2021-06-17 14:25 UTC, merged

2021-06-17 14:25 UTC, PierreRambaud commented
Thank you @Quetzacoalt91